myapp/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'myapp'
urlpatterns = [
    path('' , views.index , name='index'),
    path('product_detail/<int:product_id>/' , views.product_detail , name='product_detail'),
    path('order/<int:order_id>/' , views.after_order , name='after_order'),
    path('create_product/' , views.create_product , name='create_product'),
    path('update_product/<int:product_id>/' , views.update_product , name='update_product'),
    path('delete_product/<int:product_id>/' , views.delete_product , name='delete_product'),
    path('dashboard/' , views.dashboard ,name='dashboard'),
    path('register/' , views.register ,name='register'),
    path('login/' , auth_views.LoginView.as_view(template_name='myapp/login.html') , name='login'),
    path('logout/' , auth_views.LogoutView.as_view(template_name='myapp/logout.html') , name='logout'),
    path('invalid/' , views.invalid , name='invalid'),
    path('my_purchases/' , views.my_purchases , name='my_purchases'),
    path('sales/' , views.sales , name='sales'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('myapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Product(models.Model):
    seller = models.ForeignKey(User , on_delete=models.CASCADE , default=1)
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    price = models.FloatField()
    file = models.FileField(upload_to='products/')
    total_sales_amount = models.IntegerField(default=0)
    total_orders = models.IntegerField(default=0)

    def __str__(self):
        return self.name
    
class OrderDetail(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    customer_email = models.EmailField()
    quantity = models.IntegerField(default=1)
    amount = models.IntegerField(default=0)
    has_paid = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now_add=True)
    
    

myapp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import OrderDetail , Product

class OrderDetailForm(forms.ModelForm):
    class Meta:
        model = OrderDetail
        fields = ['quantity']
        
        widgets = {
            'quantity': forms.NumberInput(attrs={
                'id': 'numberInput',
                'class': 'w-20 outline-none border-2 border-gray-300 rounded-md px-2 py-1 focus:border-blue-300',
                'type': 'number',
                'min': 1,
                'value': 1,
                'onInput': 'resizeInput()'
            }),
        }
        
class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name' , 'description' , 'price' , 'file']
        
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'outline-none border-2 border-gray-300 rounded-md px-2 py-1 focus:border-blue-300',
            }),
            'description': forms.TextInput(attrs={
                'class': 'outline-none border-2 border-gray-300 rounded-md px-2 py-1 focus:border-blue-300',
            }),
            'price': forms.NumberInput(attrs={
                'class': 'outline-none border-2 border-gray-300 rounded-md px-2 py-1 focus:border-blue-300',
            }),
            'file': forms.FileInput(attrs={
                'class': 'outline-none border-2 border-gray-300 rounded-md px-2 py-1 focus:border-blue-300',
            }),
        }
        
class UserRegistrationForm(UserCreationForm):
    # email = forms.EmailField()
    class Meta:
        model = User
        fields = ('username','email','first_name','last_name','password1','password2')
        

myapp/views.py
from django.shortcuts import render , redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from .models import Product , OrderDetail
from .forms import OrderDetailForm , ProductForm , UserRegistrationForm
import datetime

def index(request):
    products = Product.objects.all()
    return render(request , 'myapp/index.html' , {'products': products})

def product_detail(request, product_id):    
    product = Product.objects.get(id=product_id)
    if (request.method == 'POST'):
        form = OrderDetailForm(request.POST or None)
        if (form.is_valid()):
            # user = request.user
            # print("The data is : " , form.cleaned_data.get('quantity'))
            if (request.user.id == None):
                return redirect('myapp:login')
            
            order = OrderDetail()
            order.product = product
            order.customer_email = request.user.email
            order.quantity = form.cleaned_data.get('quantity')
            order.amount = order.quantity * product.price
            order.has_paid = True
            order.save()
            
            product.total_orders += 1
            product.total_sales_amount += order.amount
            product.save()
            
            return redirect("myapp:after_order" , order_id=order.id)
        
    form = OrderDetailForm()
    return render(request, 'myapp/product_detail.html', {'product': product , 'form': form})

def after_order(request , order_id):
    order = OrderDetail.objects.get(id=order_id)
    return render(request , 'myapp/success.html' , {'order':order})

@login_required
def create_product(request):
    if (request.method == 'POST'):
        product = ProductForm(request.POST , request.FILES)
        if (product.is_valid()):
            new_product = product.save(commit=False)
            new_product.seller = request.user
            new_product.save()
            return redirect('myapp:index')
    
    product_form = ProductForm()
    return render(request , 'myapp/create_product_form.html' , {'product_form' : product_form})

@login_required
def update_product(request , product_id):
    product = Product.objects.get(id = product_id)
    if product.seller != request.user:
        return redirect('myapp:invalid')
    
    product_form = ProductForm(request.POST or None , request.FILES or None , instance=product)
    if (request.method == 'POST'):
        if (product_form.is_valid()):
            product_form.save()
            return redirect('myapp:index')
    
    return render(request , 'myapp/update_product_form.html' , {'product_form' : product_form , 'product_id' : product_id})

@login_required
def delete_product(request , product_id):    
    product = Product.objects.get(id=product_id)
    if product.seller != request.user:
        return redirect('myapp:invalid')
    
    if (request.method == 'POST'):
        product.delete()
        return redirect('myapp:index')
    
    return render(request , 'myapp/confirm_delete.html' , {'product' : product})

@login_required
def dashboard(request):
    products = Product.objects.filter(seller = request.user)
    return render(request , 'myapp/dashboard.html' , {'products' : products})

def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        user_form.save()
        return redirect('myapp:login')
    
    user_form = UserRegistrationForm()
    return render(request , 'myapp/register.html' , {'user_form': user_form})

def invalid(request):
    return render(request , 'myapp/invalid.html')

@login_required
def my_purchases(request):    
    orders = OrderDetail.objects.filter(customer_email= request.user.email)
    return render(request , 'myapp/my_purchases.html' , {'orders': orders})

@login_required
def sales(request):    
    orders = OrderDetail.objects.filter(product__seller=request.user)
    total_sales = {}
    total_sales['total'] = orders.aggregate(Sum('amount'))
    
    lst = [[7 , 'weekly'] , [30 , 'monthly'] , [365 , 'yearly']]
    for item in lst:
        var = datetime.date.today() - datetime.timedelta(item[0])
        orders = OrderDetail.objects.filter(product__seller=request.user , created_on__gt=var)
        total_sales[item[1]] = orders.aggregate(Sum('amount'))
        
    
    
    # Everyday sum for the past 30 days
    daily_sales_sums = OrderDetail.objects.filter(product__seller=request.user).values('created_on__date').order_by('created_on__date').annotate(sum = Sum('amount'))
    
    product_sales_sums = OrderDetail.objects.filter(product__seller=request.user).values('product__name').order_by('-amount').annotate(sum = Sum('amount'))
    
    
    
    context = {
        'total_sales' : total_sales,
        'daily_sales_sums' : daily_sales_sums,
        'product_sales_sums' : product_sales_sums,
    }
    
    return render(request , 'myapp/sales.html' , context)

myapp/templates/myapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link rel="shortcut icon" type="image/png" href="{% static 'myapp/icon.png' %}" >
    <link rel="stylesheet" href="{% static 'myapp/style.css' %}">
    <title>Digital Marketplace</title>
</head>
<body>

    <nav class="top-0 shadow-lg fixed z-10 w-full bg-white" id="navbar">
        <div class="flex flex-wrap justify-between p-4">
            <a class="flex items-center space-x-2" href="/">
                <img class="h-9"
                src="https://cdn4.iconfinder.com/data/icons/miu-square-gloss-social/60/app_store-square-gloss-social-media-1024.png" alt="">
                <span class="text-lg font-monospace">Digital Marketplace</span>
            </a>

            <div class="flex items-center gap-5 font-medium text-slate-gray">
                <a href="{% url 'myapp:dashboard' %}">Dashboard</a>
                <a href="{% url 'myapp:sales' %}">Sales</a>
                <a href="">Orders</a>
                <a href="{% url 'myapp:create_product' %}">Create Products</a>
                <a href="{% url 'myapp:my_purchases' %}">My Purchases</a>


                {% if user.is_authenticated %}
                    <a href="{% url 'myapp:logout' %}">Logout</a>
                {% else %}
                    <a href="{% url 'myapp:login' %}">Login</a>
                {% endif %}

            </div>
        </div>

    </nav>

    <div id="main-section">
        {% block body %}
        {% endblock %}
    </div>

    <script>
        const height = document.getElementById('navbar').offsetHeight + 10 + 'px';
        document.getElementById('main-section').style.marginTop = height;

    </script>
    
</body>
</html>

myapp/templates/myapp/confirm_delete.html
{% extends 'myapp/base.html' %}

{% block body %}

    <div class="flex flex-col justify-center items-center w-full h-[40vh]">
        <div class="font-mono">
            <span>Confirm you want to </span>
            <span class="text-red-500 font-bold">delete</span>
            <span class="font-bold text-lg text-green-600">"{{ product.name }}"</span>
        </div>
    
        <form method="POST" class="mt-6">
            <div class="flex gap-5">
                <button type="submit" class="bg-red-500 text-white py-2 px-4 rounded-full cursor-pointer hover:bg-red-600">Confirm</button>
                <a href="{% url 'myapp:index' %}" class="bg-green-500 text-white py-2 px-4 rounded-full hover:bg-green-600">No</a>
            </div>
        </form>
    </div>


{% endblock %}

myapp/templates/myapp/create_product_form.html
{% extends 'myapp/base.html' %}

{% block body %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="w-full flex justify-center items-center py-5">
        <div class="w-1/2 p-5 bg-purple-100 shadow-xl flex flex-col justify-center items-center gap-5 rounded-lg py-10">
            <div class="font-mono text-lg text-[#01838C]">
                Add Product
            </div>

            {% for field in product_form %}
                <div class="w-full">
                    {{ field.label_tag }}
                    {{ field}}
                </div>
            {% endfor %}

            <div>
                <button type="submit" class="cursor-pointer px-4 py-2 bg-green-500 text-white rounded-full hover:bg-green-600">Create</button>
            </div>
        </div>
    </div>

</form>

{% endblock %}

myapp/templates/myapp/dashboard.html
{% extends 'myapp/base.html' %}

{% block body %}

    <div class="py-3 pl-12 pr-6 space-y-10">
        <div>
            <div class="flex justify-between items-center">
                <div class="font-mono text-xl font-semibold text-[#524D4D]">
                    My Products
                </div>
                <div>
                    <a href="{% url 'myapp:create_product' %}">
                        <button class="bg-green-400 text-white rounded-full cursor-pointer py-3 px-5 hover:bg-green-500">Add Product</button>
                    </a>
                </div>
            </div>
        </div>

        <div>
            <div class="space-y-5">
                {% for product in products %}
                    <div class="group w-full grid grid-cols-2
                    shadow-lg rounded-md bg-[#FBEBFF]">
                        <div class="p-2 flex gap-3 items-center">
                            <div class="w-50 flex justify-center items-center">
                                <img src="{{ product.file.url }}" alt="{{ product.name }}" 
                                class="h-25 rounded-md">

                            </div>
                            
                            <div class="flex flex-col justify-center items-center group-hover:hidden">
                                <div class="font-mono">{{ product.name }}</div>
                                <div class="text-green-400 font-semibold">₹ {{ product.price }}</div>
                            </div>

                            <div class="ml-5 flex gap-5">
                                <div class="hidden group-hover:block">
                                    <a href="{% url 'myapp:update_product' product.id %}"><button class="px-5 py-2 rounded-full cursor-pointer bg-green-400 text-white hover:bg-green-500">Edit</button></a>
                                </div>
                                <div class="hidden group-hover:block">
                                    <a href="{% url 'myapp:delete_product' product.id %}"><button class="px-5 py-2 rounded-full cursor-pointer bg-red-400 text-white hover:bg-red-500">Delete</button></a>
                                </div>
                            </div>


                        </div>
                            

                        <div class="flex justify-between items-center">
                            <div>
                                <div class="text-2xl text-green-500">₹ {{ product.total_sales_amount }}</div>
                                <div class="text-xs">Total earnings</div>
                            </div>
                            <div>
                                <div class="text-2xl">{{ product.total_orders }}</div>
                                <div class="text-xs">Total orders</div>
                            </div>
                            <div class="pr-5">
                                <div class="text-2xl text-green-400">4.8</div>
                                <div class="text-xs">Rating</div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block body %}

<section>
    <div class="mt-10 p-5 grid grid-cols-4 gap-5">
        {% for product in products %}

            <!-- Card -->
            <div class="flex justify-center items-center">

                <div class="w-full rounded-lg shadow-xl flex flex-col items-center justify-center p-3 h-fit">
                    <div class="">
                        <!-- <img src="https://community.softr.io/uploads/db9110/original/2X/7/74e6e7e382d0ff5d7773ca9a87e6f6f8817a68a6.jpeg" alt="Image"> -->
                        <img src="{{ product.file.url }}" alt="Image"
                        class="w-full object-cover rounded-lg shadow-md change-height">
    
                    </div>
    
                    <div class="mt-2 p-4 font-mono">
                        <h1 class="font-bold text-xl my-3">{{ product.name }}</h1>
                        <p>{{ product.description }}</p>
                        <p class="text-green-600 font-bold mt-2"> ₹ {{ product.price }}</p>
                    </div>
    
                    <a href="{% url 'myapp:product_detail' product.id %}">
                        <button class="rounded-full bg-blue-500 text-white px-4 py-2 cursor-pointer hover:bg-blue-600">View Details</button>
                    </a>
    
                </div>
            </div>

        

        {% endfor %}
    </div>
</section>


<script>
    const changeHeight = document.getElementsByClassName('change-height');
    Array.from(changeHeight).forEach((element) => {
        const width = element.offsetWidth + 'px';
        element.style.maxHeight = width;
    });

</script>


{% endblock %}

myapp/templates/myapp/invalid.html
{% extends 'myapp/base.html' %}

{% block body %}

    <div class="flex flex-col justify-center items-center w-full h-[50vh]">
        <div class="font-mono flex justify-center items-center flex-col">
            <span class="text-red-500">
                You are trying to access an 
                <span class="text-red-600 font-bold">Invalid Request</span>
            </span>
            <br>

            <span>
                <span>
                    <a href="{% url 'myapp:index' %}" class="text-indigo-500">Click Here</a>
                    to go to home page</span>
            </span>


        </div>
    </div>


{% endblock %}

myapp/templates/myapp/login.html
{% extends 'myapp/base.html' %}

{% block body %}

    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Submit</button>
    </form>



{% endblock %}

myapp/templates/myapp/logout.html
{% extends 'myapp/base.html' %}

{% block body %}

    You are sucessfully logged out

{% endblock %}

myapp/templates/myapp/my_purchases.html
{% extends 'myapp/base.html' %}

{% block body %}


    <div class="py-3 pl-12 pr-6 space-y-10">
        <div>
            <div class="flex justify-center items-center">
                <div class="font-mono text-xl font-semibold text-[#524D4D]">
                    My Purchases
                </div>
            </div>
        </div>

        <div class="shadow-xl px-4 py-8">
            <div class="grid grid-cols-4 gap-y-4">
                <div class="font-mono font-bold flex justify-center">Product Name</div>
                <div class="font-mono font-bold flex justify-center">Quantity</div>
                <div class="font-mono font-bold flex justify-center">Purchase Date</div>
                <div class="font-mono font-bold flex justify-center">Download Link</div>

                <hr><hr><hr><hr>

                {% for order in orders %} 
                    <div class="flex justify-center font-mono">
                        <a href="{% url 'myapp:product_detail' order.product.id %}">{{ order.product.name }}</a>
                    </div>
                    <div class="flex justify-center text-green-500">{{ order.quantity }}</div>
                    <div class="flex justify-center">{{ order.created_on }}</div>
                    <div class="flex justify-center space-x-1">
                        <a href="{{ order.product.file.url }}" download class="text-indigo-400">Click Here</a> 
                        <span>to Download</span>
                    </div>


                {% endfor %}
                
            </div>
        </div>
    </div>


{% endblock %}


                {% for product in orders %}
                    <div class="group w-full grid grid-cols-2
                    shadow-lg rounded-md bg-[#FBEBFF]">
                        <div class="p-2 flex gap-3 items-center">
                            <div class="w-50 flex justify-center items-center">
                                <!-- <img src="" alt="" 
                                class="h-25 rounded-md"> -->

                            </div>

                            <div class="ml-5 flex gap-5">
                                <div class="hidden group-hover:block">
                                    <a href=""><button class="px-5 py-2 rounded-full cursor-pointer bg-green-400 text-white hover:bg-green-500">Edit</button></a>
                                </div>
                                <div class="hidden group-hover:block">
                                    <a href=""><button class="px-5 py-2 rounded-full cursor-pointer bg-red-400 text-white hover:bg-red-500">Delete</button></a>
                                </div>
                            </div>


                        </div>
                            

                        <div class="flex justify-between items-center">
                            <div>
                                <div class="text-2xl text-green-500">₹ 60000</div>
                                <div class="text-xs">Total earnings</div>
                            </div>
                            <div>
                                <div class="text-2xl">50</div>
                                <div class="text-xs">Total orders</div>
                            </div>
                            <div class="pr-5">
                                <div class="text-2xl text-green-400">4.8</div>
                                <div class="text-xs">Rating</div>
                            </div>
                        </div>
                    </div>
                {% endfor %}    

myapp/templates/myapp/product_detail.html
{% extends 'myapp/base.html' %}

{% block body %}

<section>
    <div class="pl-10 pt-10 font-mono">
        <div class="flex gap-5">
            <div>
                <div id="check-width" class="w-130 flex items-center justify-center">
                    <img 
                    class="rounded-md change-height"
                    src="{{ product.file.url }}" alt="{{ product.name }}">
                </div>
            </div>
            <div class="ml-10">
                <p class="text-4xl my-4 font-semibold">{{ product.name }}</p>
                <p>{{ product.description }}</p>
                <p class="my-2 font-bold text-green-500">₹ {{ product.price }}</p>

                <button class="my-3 rounded-full bg-blue-500 text-white px-4 py-2 cursor-pointer" id="buyNowButton" onclick="showQuantity()">
                    Buy Now
                </button>

                <form method="POST" id="quantityForm" class="hidden my-4">
                    {% csrf_token %}

                    <div class="mb-3">

                        {% for field in form %}
                            <div>
                                {{ field.label_tag }}
                                {{ field }}
                            </div>
                        {% endfor %}
                        
                    </div>
                    <button type="submit" class="my-3 rounded-full bg-blue-500 text-white px-4 py-2 cursor-pointer">
                        Buy Now
                    </button>
                </form>
            </div>

        </div>
    </div>
</section>

<script>
    const resizeInput = () => {
        const input = document.getElementById('numberInput');
        input.style.width = `${input.value.length + 8}ch`;
    }

    const showQuantity = () => {
        const quantityForm = document.getElementById('quantityForm');
        quantityForm.classList.toggle('hidden');

        const buyNowButton = document.getElementById('buyNowButton');
        buyNowButton.classList.toggle('hidden');
    }

    const changeHeight = document.getElementsByClassName('change-height');
    Array.from(changeHeight).forEach((element) => {
        const width = document.getElementById('check-width').offsetWidth + 'px';
        element.style.maxHeight = width;
    });
</script>

{% endblock %}

myapp/templates/myapp/sales.html
{% extends 'myapp/base.html' %}

{% block body %}

    <div class="py-3 pl-12 pr-6 space-y-10">
        <div>
            <div class="flex justify-between items-center">
                <div class="font-mono text-xl font-semibold">
                    Sales Stats
                </div>
                <div>
                    <a href="{% url 'myapp:dashboard' %}">
                        <button class="bg-green-400 text-white rounded-full cursor-pointer py-3 px-5 hover:bg-green-500">Dashboard</button>
                    </a>
                </div>
            </div>
        </div>

        <div class="shadow-lg p-5">
            <div>
                <div class="text-5xl font-bold text-green-500 mb-6">₹ {{ total_sales.total.amount__sum }}</div>
                <div class="text-sm">Your Lifetime Revenue</div>
            </div>
        </div>

        <div class="grid grid-cols-3 gap-10">
            <div class="shadow-lg p-4">
                <div class="text-3xl font-bold mb-4">₹ {{ total_sales.yearly.amount__sum }}</div>
                <div class="text-sm">Last 365 Days</div>
            </div>
            <div class="shadow-lg p-4">
                <div class="text-3xl font-bold mb-4">₹ {{ total_sales.monthly.amount__sum }}</div>
                <div class="text-sm">Last 30 Days</div>
            </div>
            <div class="shadow-lg p-4">
                <div class="text-3xl font-bold mb-4">₹ {{ total_sales.weekly.amount__sum }}</div>
                <div class="text-sm">Last 7 Days</div>
            </div>
        </div>

        <div class="flex w-full">
            <div class="shadow-lg p-5 rounded-md w-1/2 h-fit">
                <div class="font-bold font-mono mb-5 text-lg w-full flex justify-center">
                    30 Day Sales
                </div>
    
                <div class="grid grid-cols-2 gap-y-3">
                    <div class="font-bold flex justify-center">Day</div>
                    <div class="font-bold flex justify-center">Total Sales</div>
    
                    <hr><hr>
    
                    {% for daily_sales in daily_sales_sums %}
                        <div class="flex justify-center daily-date">{{ daily_sales.created_on__date }}</div>
                        <div class="flex justify-center font-bold text-green-600 daily-sales">₹ {{ daily_sales.sum }}</div>
    
                    {% endfor %}
    
                </div>
    
            </div>

            <div class="w-1/2 ml-5 shadow-lg p-5">
                <div class="w-full flex justify-center font-mono font-semibold mb-5">30 Days Sales</div>
                <canvas id="daily-sales-chart"></canvas>
            </div>
        </div>


        <div class="flex w-full">
            <div class="w-1/2 mr-2">
                <div class="w-full flex justify-center font-mono font-semibold mb-5">Products Sales</div>
                <canvas id="product-sales-chart"></canvas>
            </div>

            <div class="shadow-lg p-5 rounded-md w-1/2 h-fit">
                <div class="font-bold font-mono mb-5 text-lg w-full flex justify-center">
                    Product Sales
                </div>
    
                <div class="grid grid-cols-2 gap-y-3">
                    <div class="font-bold flex justify-center">Product Name</div>
                    <div class="font-bold flex justify-center">Total Sales</div>
    
                    <hr><hr>
    
                    {% for product_sales in product_sales_sums %}
                        <div class="flex justify-center product-name">{{ product_sales.product__name }}</div>
                        <div class="flex justify-center font-bold text-green-600 product-sales">₹ {{ product_sales.sum }}</div>
    
                    {% endfor %}
    
                </div>
    
            </div>
        </div>

    </div>

    
    <script>
        const daily_dates = []
        const daily_sales = []
        const dates_elements = document.getElementsByClassName('daily-date')
        const dates_sums = document.getElementsByClassName('daily-sales')
        for (let i = 0;i< dates_elements.length ;i++){
            daily_dates.push(dates_elements[i].innerText);
            daily_sales.push(parseInt(dates_sums[i].innerText.slice(2)))
        }

        new Chart(document.getElementById('daily-sales-chart'), {
            type: 'line',
            data: {
                labels: daily_dates,
                datasets: [{
                    label: 'Day Sales',
                    data: daily_sales,
                    fill: false,
                    borderColor: 'rgb(75, 192, 192)',
                    tension: 0.1
                }]
            }
        });
    

        
        const product_name = []
        const product_sale = []
        const product_elements = document.getElementsByClassName('product-name')
        const product_sums = document.getElementsByClassName('product-sales')
        for (let i = 0;i< product_elements.length ;i++){
            product_name.push(product_elements[i].innerText);
            product_sale.push(parseInt(product_sums[i].innerText.slice(2)))
        }

        new Chart(document.getElementById('product-sales-chart'), {
            type: 'pie',
            data: {
                labels: product_name,
                datasets: [{
                    label: 'My First Dataset',
                    data: product_sale,

                    hoverOffset: 4
                }]
            },
        });

    </script>

{% endblock %}

            backgroundColor: [
                'rgb(255, 99, 132)',
                'rgb(54, 162, 235)',
                'rgb(255, 205, 86)'
            ],

myapp/templates/myapp/update_product_form.html
{% extends 'myapp/base.html' %}

{% block body %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="w-full flex justify-center items-center py-5">
        <div class="w-1/2 p-5 bg-purple-100 shadow-xl flex flex-col justify-center items-center gap-5 rounded-lg py-10">
            <div class="font-mono text-lg text-[#01838C]">
                Edit Product
            </div>

            {% for field in product_form %}
                <div class="w-full">
                    {{ field.label_tag }}
                    {{ field}}
                </div>
            {% endfor %}

            <div>
                <button type="submit" class="cursor-pointer px-4 py-2 bg-green-500 text-white rounded-full hover:bg-green-600">Update</button>

                <!-- <a href="{% url 'myapp:delete_product' product_id %}">
                    <button class="cursor-pointer px-4 py-2 bg-[#FF4040] text-white rounded-full hover:bg-[#F70707]">Delete</button>
                </a> -->
            </div>
        </div>
    </div>

</form>

{% endblock %}